; ;***********************無変換ショートカット*****************************************************
SC07B::Send("+{F13}") ;[無変換] -> [日本語入力モード]

;***********************無変換キー基本動作定義*****************************************************
SC07B & a::Send("{Blind}^{a}") ;[無変換] + [a] -> [ctrla]
SC07B & b::Send("{Blind}^{b}") ;[無変換] + [b] -> [ctrlb]
SC07B & c::Send("{Blind}^{c}") ;[無変換] + [c] -> [ctrlc]
SC07B & d::Send("{Blind}^{d}") ;[無変換] + [d] -> [ctrld]
SC07B & e::Send("{Blind}^{e}") ;[無変換] + [e] -> [ctrle]
SC07B & f::Send("{Blind}^{f}") ;[無変換] + [f] -> [ctrlf]
SC07B & g::Send("{Blind}^{g}") ;[無変換] + [g] -> [ctrlg]
SC07B & h::Send("{Blind}^{h}") ;[無変換] + [h] -> [ctrlh]
SC07B & i::Send("{Blind}^{i}") ;[無変換] + [i] -> [ctrli]
SC07B & j::Send("{Blind}^{j}") ;[無変換] + [j] -> [ctrlj]
SC07B & k::Send("{Blind}^{k}") ;[無変換] + [k] -> [ctrlk]
SC07B & l::Send("{Blind}^{l}") ;[無変換] + [l] -> [ctrll]
SC07B & m::Send("{Blind}^{m}") ;[無変換] + [m] -> [ctrlm]
SC07B & n::Send("{Blind}^{n}") ;[無変換] + [n] -> [ctrln]
SC07B & o::Send("{Blind}^{o}") ;[無変換] + [o] -> [ctrlo]
SC07B & p::Send("{Blind}^{p}") ;[無変換] + [p] -> [ctrlp]
SC07B & q::Send("{Blind}^{q}") ;[無変換] + [q] -> [ctrlq]
SC07B & r::Send("{Blind}^{r}") ;[無変換] + [r] -> [ctrlr]
SC07B & s::Send("{Blind}^{s}") ;[無変換] + [s] -> [ctrls]
SC07B & t::Send("{Blind}^{t}") ;[無変換] + [t] -> [ctrlt]
SC07B & u::Send("{Blind}^{u}") ;[無変換] + [u] -> [ctrlu]
SC07B & v::Send("{Blind}^{v}") ;[無変換] + [v] -> [ctrlv]
SC07B & w::Send("{Blind}^{w}") ;[無変換] + [w] -> [ctrlw]
SC07B & x::Send("{Blind}^{x}") ;[無変換] + [x] -> [ctrlx]
SC07B & y::Send("{Blind}^{y}") ;[無変換] + [y] -> [ctrly]
SC07B & z::Send("{Blind}^{z}") ;[無変換] + [z] -> [ctrlz]

SC07B & 1::Send("{Blind}^{1}") ;[無変換] + [1] -> [ctrl + 1]
SC07B & 2::Send("{Blind}^{2}") ;[無変換] + [2] -> [ctrl + 2]
SC07B & 3::Send("{Blind}^{3}") ;[無変換] + [3] -> [ctrl + 3]
SC07B & 4::Send("{Blind}^{4}") ;[無変換] + [4] -> [ctrl + 4]
SC07B & 5::Send("{Blind}^{5}") ;[無変換] + [5] -> [ctrl + 5]
SC07B & 6::Send("{Blind}^{6}") ;[無変換] + [6] -> [ctrl + 6]
SC07B & 7::Send("{Blind}^{7}") ;[無変換] + [7] -> [ctrl + 7]
SC07B & 8::Send("{Blind}^{8}") ;[無変換] + [8] -> [ctrl + 8]
SC07B & 9::Send("{Blind}^{9}") ;[無変換] + [9] -> [ctrl + 9]
SC07B & 0::Send("{Blind}^{0}") ;[無変換] + [0] -> [ctrl + 0]
