;====================デフォルト動作定義====================
; コメントアウト済みのキーはそのキーをトリガーとした
; ショートカットが定義されている
;=======================================

; ==================== 英字 ====================
a::Send("{Blind}{a}") ;[a] -> [a]
b::Send("{Blind}{b}") ;[b] -> [b]
c::Send("{Blind}{c}") ;[c] -> [c]
d::Send("{Blind}{d}") ;[d] -> [d]
e::Send("{Blind}{e}") ;[e] -> [e]
f::Send("{Blind}{f}") ;[f] -> [f]
g::Send("{Blind}{g}") ;[g] -> [g]
h::Send("{Blind}{h}") ;[h] -> [h]
i::Send("{Blind}{i}") ;[i] -> [i]
j::Send("{Blind}{j}") ;[j] -> [j]
k::Send("{Blind}{k}") ;[k] -> [k]
l::Send("{Blind}{l}") ;[l] -> [l]
m::Send("{Blind}{m}") ;[m] -> [m]
n::Send("{Blind}{n}") ;[n] -> [n]
o::Send("{Blind}{o}") ;[o] -> [o]
p::Send("{Blind}{p}") ;[p] -> [p]
; q::Send("{Blind}{q}") ;[q] -> [q]
r::Send("{Blind}{r}") ;[r] -> [r]
s::Send("{Blind}{s}") ;[s] -> [s]
t::Send("{Blind}{t}") ;[t] -> [t]
u::Send("{Blind}{u}") ;[u] -> [u]
v::Send("{Blind}{v}") ;[v] -> [v]
w::Send("{Blind}{w}") ;[w] -> [w]
x::Send("{Blind}{x}") ;[x] -> [x]
y::Send("{Blind}{y}") ;[y] -> [y]

; ==================== 数字 ====================
; 1::Send("{Blind}{1}") ;[1] -> [1]
; 2::Send("{Blind}{2}") ;[2] -> [2]
; 3::Send("{Blind}{3}") ;[3] -> [3]
; 4::Send("{Blind}{4}") ;[4] -> [4]
; 5::Send("{Blind}{5}") ;[5] -> [5]
; 6::Send("{Blind}{6}") ;[6] -> [6]
; 7::Send("{Blind}{7}") ;[7] -> [7]
; 8::Send("{Blind}{8}") ;[8] -> [8]
; 9::Send("{Blind}{9}") ;[9] -> [9]
; 0::Send("{Blind}{0}") ;[0] -> [0]

; ==================== Fキー ====================
F1::Send("{Blind}{F1}") ;[F1] -> [F1]
F2::Send("{Blind}{F2}") ;[F2] -> [F2]
F3::Send("{Blind}{F3}") ;[F3] -> [F3]
F4::Send("{Blind}{F4}") ;[F4] -> [F4]
F5::Send("{Blind}{F5}") ;[F5] -> [F5]
F6::Send("{Blind}{F6}") ;[F6] -> [F6]
F7::Send("{Blind}{F7}") ;[F7] -> [F7]
F8::Send("{Blind}{F8}") ;[F8] -> [F8]
F9::Send("{Blind}{F9}") ;[F9] -> [F9]
F10::Send("{Blind}{F10}") ;[F10] -> [F10]
F11::Send("{Blind}{F11}") ;[F11] -> [F11]
; F12::Send("{Blind}{F12}") ;[F12] -> [F12]

; ==================== 記号 ====================
; -::Send("{Blind}{-}") ;[-] -> [-]
; ^::Send("{Blind}{^}") ;[^] -> [^]
; \::Send("{Blind}{\}") ;[\] -> [\]
; @::Send("{Blind}{@}") ;[@] -> [@]
; [::Send("{Blind}{[}") ;[[] -> [[]
; ]::Send("{Blind}{]}") ;[]] -> []]
; SC027::Send("{Blind}{SC027}") ;[SC027] -> [SC027]
; SC028::Send("{Blind}{SC028}") ;[SC028] -> [SC028]
; SC033::Send("{Blind}{SC033}") ;[SC033] -> [SC033]
; .::Send("{Blind}{.}") ;[.] -> [.]
; /::Send("{Blind}{/}") ;[/] -> [/]

; ==================== 特殊 ====================
Space::Send("{Blind}{Space}") ;[Space] -> [Space]
; Tab::Send("{Blind}{Tab}") ;[Tab] -> [Tab]
Enter::Send("{Blind}{Enter}") ;[Enter] -> [Enter]
Backspace::Send("{Blind}{Backspace}") ;[Backspace] -> [Backspace]
Delete::Send("{Blind}{Delete}") ;[Delete] -> [Delete]
; Insert::Send("{Blind}{Insert}") ;[Insert] -> [Insert]
Left::Send("{Blind}{Left}") ;[Left] -> [Left]
Right::Send("{Blind}{Right}") ;[Right] -> [Right]
Up::Send("{Blind}{Up}") ;[Up] -> [Up]
Down::Send("{Blind}{Down}") ;[Down] -> [Down]
; Esc::Send("{Blind}{Esc}") ;[Esc] -> [Esc]
AppsKey::Send("{Blind}{AppsKey}") ;[AppsKey] -> [AppsKey]


