;====================デフォルト動作定義====================
; コメントアウト済みのキーはそのキーをトリガーとした
; ショートカットが定義されている
;=======================================

; ==================== 英字 ====================
~a::Return ;[a] -> [a]
~b::Return ;[b] -> [b]
~c::Return ;[c] -> [c]
~d::Return ;[d] -> [d]
~e::Return ;[e] -> [e]
~f::Return ;[f] -> [f]
~g::Return ;[g] -> [g]
~h::Return ;[h] -> [h]
~i::Return ;[i] -> [i]
~j::Return ;[j] -> [j]
~k::Return ;[k] -> [k]
~l::Return ;[l] -> [l]
~m::Return ;[m] -> [m]
~n::Return ;[n] -> [n]
~o::Return ;[o] -> [o]
~p::Return ;[p] -> [p]
; ~q::Return ;[q] -> [q]
~r::Return ;[r] -> [r]
~s::Return ;[s] -> [s]
~t::Return ;[t] -> [t]
~u::Return ;[u] -> [u]
~v::Return ;[v] -> [v]
~w::Return ;[w] -> [w]
~x::Return ;[x] -> [x]
~y::Return ;[y] -> [y]
; ~z::Return ;[z] -> [z]


; ==================== 数字 ====================
; ~1::Return ;[1] -> [1]
; ~2::Return ;[2] -> [2]
; ~3::Return ;[3] -> [3]
; ~4::Return ;[4] -> [4]
; ~5::Return ;[5] -> [5]
; ~6::Return ;[6] -> [6]
; ~7::Return ;[7] -> [7]
; ~8::Return ;[8] -> [8]
; ~9::Return ;[9] -> [9]
; ~0::Return ;[0] -> [0]

; ==================== Fキー ====================
~F1::Return ;[F1] -> [F1]
~F2::Return ;[F2] -> [F2]
~F3::Return ;[F3] -> [F3]
~F4::Return ;[F4] -> [F4]
~F5::Return ;[F5] -> [F5]
~F6::Return ;[F6] -> [F6]
~F7::Return ;[F7] -> [F7]
~F8::Return ;[F8] -> [F8]
~F9::Return ;[F9] -> [F9]
~F10::Return ;[F10] -> [F10]
~F11::Return ;[F11] -> [F11]
; ~F12::Return ;[F12] -> [F12]

; ==================== 記号 ====================
; ~-::Return -> [-]
; ~^::Return -> [^]
; ~\::Return -> [\]
; ~@::Return -> [@]
; ~[::Return -> [[]
; ~]::Return -> []]
; ~SC027::Return ;[SC027] -> [SC027]
; ~SC028::Return ;[SC028] -> [SC028]
; ~SC033::Return ;[SC033] -> [SC033]
; ~.::Return -> [.]
; ~/::Return -> [/]

; ==================== 特殊 ====================
~Space::Return ;[Space] -> [Space]
; ~Tab::Return ;[Tab] -> [Tab]
~Enter::Return ;[Enter] -> [Enter]
~Backspace::Return ;[Backspace] -> [Backspace]
~Delete::Return ;[Delete] -> [Delete]
; ~Insert::Return ;[Insert] -> [Insert]
~Left::Return ;[Left] -> [Left]
~Right::Return ;[Right] -> [Right]
~Up::Return ;[Up] -> [Up]
~Down::Return ;[Down] -> [Down]
; ~Esc::Return ;[Esc] -> [Esc]
~AppsKey::Return ;[AppsKey] -> [AppsKey]
